"""
Round-trip contract tests between ingest and worker queue job implementations.

Verifies that payloads generated by bot-ingest-function's build_job_payload()
survive the full Pub/Sub push envelope round trip (JSON -> base64, as a real
publish/push delivery would do) and are correctly decoded and parsed by
bot-worker-function's unwrap_pubsub_envelope() + parse_job_payload().

Both apps define their own top-level `app` package (no shared package
between them — see test_shared_module_parity.py), so they can't both sit on
sys.path at once without one shadowing the other. _load_app_module() below
loads one app's `app.queue_job` fully (letting its own internal
`from app.config import settings` resolve correctly against ITS OWN
app/config.py), captures a direct reference to the resulting module object,
then purges sys.path/sys.modules before the next app is loaded — the
captured module objects stay valid afterward since Python doesn't
tear down an object just because sys.modules stops referencing it.
"""
import base64
import importlib
import json
import pathlib
import sys

import pytest

_GCP_QUEUE_ROOT = pathlib.Path(__file__).resolve().parents[2]


def _load_app_module(app_root: pathlib.Path, dotted_name: str):
    for name in [m for m in sys.modules if m == "app" or m.startswith("app.")]:
        del sys.modules[name]

    root_str = str(app_root)
    sys.path.insert(0, root_str)
    try:
        module = importlib.import_module(dotted_name)
    finally:
        sys.path.remove(root_str)

    for name in [m for m in sys.modules if m == "app" or m.startswith("app.")]:
        del sys.modules[name]

    return module


ingest_queue_job = _load_app_module(_GCP_QUEUE_ROOT / "bot-ingest-function", "app.queue_job")
worker_queue_job = _load_app_module(_GCP_QUEUE_ROOT / "bot-worker-function", "app.queue_job")


def _as_push_envelope(payload: dict, message_id: str = "msg-1") -> dict:
    """What Pub/Sub's push request body actually looks like for this payload."""
    data = base64.b64encode(json.dumps(payload).encode("utf-8")).decode("ascii")
    return {"message": {"data": data, "messageId": message_id}, "subscription": "projects/x/subscriptions/y"}


def test_build_then_full_push_round_trip_preserves_activity_and_placeholder_id():
    activity_body = {"type": "message", "id": "a1", "text": "hello", "conversation": {"id": "c1"}}
    payload = ingest_queue_job.build_job_payload(activity_body, loading_activity_id="placeholder-1")

    envelope = _as_push_envelope(payload)
    decoded_payload, message_id = worker_queue_job.unwrap_pubsub_envelope(envelope)
    parsed_activity, loading_activity_id, enqueued_at = worker_queue_job.parse_job_payload(decoded_payload)

    assert message_id == "msg-1"
    assert parsed_activity == activity_body
    assert loading_activity_id == "placeholder-1"
    assert enqueued_at.tzinfo is not None


def test_build_then_full_push_round_trip_with_no_placeholder():
    activity_body = {"type": "message", "id": "a2", "text": "hi", "conversation": {"id": "c2"}}
    payload = ingest_queue_job.build_job_payload(activity_body, loading_activity_id=None)

    envelope = _as_push_envelope(payload)
    decoded_payload, _ = worker_queue_job.unwrap_pubsub_envelope(envelope)
    parsed_activity, loading_activity_id, _ = worker_queue_job.parse_job_payload(decoded_payload)

    assert parsed_activity == activity_body
    assert loading_activity_id is None


def test_worker_rejects_a_payload_missing_the_activity_object():
    with pytest.raises(worker_queue_job.InvalidJobPayload):
        worker_queue_job.parse_job_payload({"loadingActivityId": "x", "enqueuedAt": "2024-01-01T00:00:00Z"})


def test_worker_rejects_an_envelope_with_no_message_key():
    with pytest.raises(worker_queue_job.InvalidJobPayload):
        worker_queue_job.unwrap_pubsub_envelope({"subscription": "projects/x/subscriptions/y"})


def test_worker_rejects_non_base64_message_data():
    with pytest.raises(worker_queue_job.InvalidJobPayload):
        worker_queue_job.unwrap_pubsub_envelope({"message": {"data": "not-valid-base64!!!", "messageId": "m1"}})


def test_worker_rejects_base64_that_is_not_json():
    not_json = base64.b64encode(b"not json at all").decode("ascii")
    with pytest.raises(worker_queue_job.InvalidJobPayload):
        worker_queue_job.unwrap_pubsub_envelope({"message": {"data": not_json, "messageId": "m1"}})


def test_installation_update_remove_kind_round_trips():
    activity_body = {"type": "installationUpdate", "action": "remove", "conversation": {"id": "c3"}}
    payload = ingest_queue_job.build_job_payload(activity_body, None, kind="installationUpdateRemove")

    envelope = _as_push_envelope(payload)
    decoded_payload, _ = worker_queue_job.unwrap_pubsub_envelope(envelope)

    assert worker_queue_job.get_job_kind(decoded_payload) == "installationUpdateRemove"
